spring:
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 10
      connection-timeout: 5000
    url: jdbc:postgresql://localhost:5433/product_manager_db?charSet=UNICODE
    username: product_manager_user
    password: abc123
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  mvc:
    locale: en

server:
  port: 8080


game-app:
  url: http://localhost:8080/games/