spring:
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 10
      connection-timeout: 5000
    url: jdbc:postgresql://localhost:5434/shoppingcartdb?charSet=UNICODE
    username: shoppingcartuser
    password: abc123
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  mvc:
    locale: en

server:
  port: 8082


rabbitmq:
  host: localhost
  port: 5672
  producer-queue:
    name: invoiceToPay
  consumer-queue:
    name: invoiceResult

purchase-history-app:
  url: http://localhost:8080/purchase-history/